version: '3.7'

networks:
  ioet:
    name: ioet
    driver: bridge

services:

  web:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./app:/usr/share/nginx/html
    networks:
      - ioet

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - ioet